<?php declare(strict_types=1);

namespace Neusta\Pimcore\HttpCacheBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('neusta_pimcore_http_cache');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->fixXmlConfig('element')
            ->fixXmlConfig('cache_type')
            ->children()
                ->enumNode('scope')
                    ->info('When to start collecting cache tags. "controller" (default): only from kernel.controller onwards, elements loaded before (e.g. in kernel.request listeners) are not tagged. "request": collect from the very beginning of the request.')
                    ->values(['controller', 'request'])
                    ->defaultValue('controller')
                ->end()
                    ->booleanNode('tag_fallback_document')
                    ->info('Whether to tag the response with the document found in the request (DynamicRouter::CONTENT_KEY) when it is only a fallback, i.e. it was not resolved by the matched route itself but is merely the nearest document by path. Default: false.')
                    ->defaultFalse()
                ->end()
                ->arrayNode('elements')
                    ->info('Controls which element types are tracked.')
                    ->addDefaultsIfNotSet()
                    ->fixXmlConfig('asset')
                    ->fixXmlConfig('document')
                    ->fixXmlConfig('object')
                    ->children()
                        ->arrayNode('assets')
                            ->fixXmlConfig('type')
                            ->canBeDisabled()
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('types')
                                    ->info('Enable/disable cache handling for asset types.')
                                    ->beforeNormalization()
                                        ->always(static fn ($v) => $v + ['folder' => false])
                                    ->end()
                                    ->normalizeKeys(false)
                                    ->useAttributeAsKey('type')
                                    ->defaultValue(['folder' => false])
                                    ->booleanPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('documents')
                            ->fixXmlConfig('type')
                            ->canBeDisabled()
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('types')
                                    ->info('Enable/disable cache handling for document types.')
                                    ->beforeNormalization()
                                        ->always(static fn ($v) => $v + ['email' => false, 'folder' => false, 'hardlink' => false])
                                    ->end()
                                    ->normalizeKeys(false)
                                    ->useAttributeAsKey('type')
                                    ->defaultValue(['email' => false, 'folder' => false, 'hardlink' => false])
                                    ->booleanPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('objects')
                            ->fixXmlConfig('type')
                            ->fixXmlConfig('class')
                            ->canBeDisabled()
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('types')
                                    ->info('Enable/disable cache handling for data object types.')
                                    ->beforeNormalization()
                                        ->always(static fn ($v) => $v + ['folder' => false])
                                    ->end()
                                    ->normalizeKeys(false)
                                    ->useAttributeAsKey('type')
                                    ->defaultValue(['folder' => false])
                                    ->booleanPrototype()->end()
                                ->end()
                                ->arrayNode('classes')
                                    ->info('Enable/disable cache handling for data object classes.')
                                    ->normalizeKeys(false)
                                    ->useAttributeAsKey('class')
                                    ->defaultValue([])
                                    ->booleanPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('cache_types')
                    ->info('Enable/disable cache handling for custom cache types.')
                    ->normalizeKeys(false)
                    ->useAttributeAsKey('type')
                    ->booleanPrototype()->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
